version: '3.9'

services:
  nuxt:
    build: .
    container_name: nuxt3-container
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
